#!/usr/bin/env python3
"""Generate the iPXE menu from ready entries in the OS catalog."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def load_catalog(path: Path) -> list[dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    return [entry for entry in data["operating_systems"] if entry.get("status") == "ready"]


def generate(entries: list[dict]) -> str:
    lines = [
        "#!ipxe",
        "",
        "# Generated by scripts/generate-ipxe-menu.py.",
        "# Only ready catalog entries with kernel+initrd artifacts are included.",
        "",
        "menu NetInstall - Select an operating system",
    ]
    for entry in entries:
        lines.append(f"item {entry['id']} {entry['name']} {entry['version']} (network installer)")
    lines.append("item shell iPXE shell")
    lines += ["choose selected || goto shell", "", "goto ${selected}", ""]

    for entry in entries:
        artifacts = {artifact["name"]: artifact["url"] for artifact in entry["artifacts"]}
        if "kernel" not in artifacts or "initrd" not in artifacts:
            raise ValueError(f"{entry['id']} has no kernel/initrd pair")
        lines += [
            f":{entry['id']}",
            f"echo Loading {entry['name']} {entry['version']} network installer...",
            f"kernel {artifacts['kernel']} ip=dhcp ---",
            f"initrd {artifacts['initrd']}",
            "boot",
            "",
        ]

    lines += [":shell", "shell"]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog", type=Path, default=ROOT / "catalog" / "operating-systems.json")
    parser.add_argument("--output", type=Path, default=ROOT / "boot" / "ipxe" / "menu.ipxe")
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate(load_catalog(args.catalog)), encoding="utf-8")
    print(f"Generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
